apiVersion: v1
kind: ConfigMap
metadata:
  name: k3s-config
  namespace: kube-system
data:
  config.yaml: |
    # K3s server configuration
    disable:
      - traefik
      - servicelb
    kubelet-arg:
      - "eviction-hard=memory.available<100Mi"
      - "eviction-soft=memory.available<300Mi"
      - "eviction-soft-grace-period=memory.available=30s"
      - "system-reserved=memory=200Mi"
      - "kube-reserved=memory=100Mi"

