version: '3.8'

# Database stack profile
include:
  - ../base/docker-compose.yml
  - ../services/postgresql.yml
  - ../services/redis.yml

# Override atau tambahan konfigurasi untuk database stack
services:
  postgresql:
    environment:
      POSTGRES_DB: ${DB_NAME:-appdb}
      POSTGRES_USER: ${DB_USER:-appuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_123}

  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_secure_123}
