version: '3.8'

# Complete monitoring stack profile dengan system monitoring
include:
  - ../base/docker-compose.yml
  - ../services/prometheus.yml
  - ../services/grafana.yml
  - ../services/monitoring-exporters.yml

# Override untuk monitoring stack lengkap
services:
  prometheus:
    environment:
      PROMETHEUS_RETENTION: ${MONITORING_RETENTION:-7d}
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/rules:/etc/prometheus/rules:ro

  grafana:
    environment:
      GF_SECURITY_ADMIN_USER: ${MONITORING_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${MONITORING_PASSWORD:-admin123}
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/system-overview.json
