version: '3.8'

services:
  redis:
    <<: *common-variables
    image: redis:7.2-alpine
    container_name: infra-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123} --maxmemory 128mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    # Resource limits for 1GB RAM VPS
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
    logging: *default-logging
    labels:
      - "traefik.enable=false"
