apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  postgresql.conf: |
    # PostgreSQL configuration optimized for low memory
    shared_buffers = {{ .Values.postgresqlConfig.shared_buffers }}
    effective_cache_size = {{ .Values.postgresqlConfig.effective_cache_size }}
    maintenance_work_mem = {{ .Values.postgresqlConfig.maintenance_work_mem }}
    work_mem = {{ .Values.postgresqlConfig.work_mem }}
    max_connections = {{ .Values.postgresqlConfig.max_connections }}

    # Logging
    log_statement = 'none'
    log_min_duration_statement = 1000

    # Checkpoints
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB

    # Random page cost
    random_page_cost = 1.1

