{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.password }}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}

